# Generated by Django 4.2.2 on 2023-08-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conjugaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_valide', models.BooleanField(default=False)),
                ('texte', models.TextField(null=True)),
                ('prnm_je', models.CharField(max_length=30, null=True)),
                ('prnm_nous', models.CharField(max_length=30, null=True)),
                ('prnm_tu_M', models.CharField(max_length=30, null=True)),
                ('prnm_tu_F', models.CharField(max_length=30, null=True)),
                ('prnm_vous_2M', models.CharField(max_length=30, null=True)),
                ('prnm_vous_PM', models.CharField(max_length=30, null=True)),
                ('prnm_vous_PF', models.CharField(max_length=30, null=True)),
                ('prnm_il', models.CharField(max_length=30, null=True)),
                ('prnm_elle', models.CharField(max_length=30, null=True)),
                ('prnm_ils_2', models.CharField(max_length=30, null=True)),
                ('prnm_ils_P', models.CharField(max_length=30, null=True)),
                ('prnm_elles_P', models.CharField(max_length=30, null=True)),
                ('temps', models.CharField(choices=[('A', 'الماضي'), ('B', 'المضارع'), ('C', 'المضارع المنصوب'), ('D', 'الماضي المبني للمجهول'), ('E', 'المضارع المبني للمجهول'), ('F', 'المضارع المجزوم'), ('G', 'الأمر')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(null=True)),
                ('est_valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField(null=True)),
                ('est_valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lemme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemme', models.CharField(max_length=15)),
                ('freq_brute', models.IntegerField()),
                ('freq_relative', models.DecimalField(decimal_places=10, max_digits=12)),
                ('rank', models.BigIntegerField(null=True)),
                ('niveau2', models.IntegerField(default=0, null=True)),
                ('categories', models.CharField(max_length=17)),
                ('syn_texte', models.TextField(null=True)),
                ('ant_texte', models.TextField(null=True)),
                ('antonymes', models.ManyToManyField(related_name='antonymes', to='core.lemme')),
                ('antonymes_valides', models.ManyToManyField(related_name='antonymes', to='core.lemme')),
            ],
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=15)),
                ('analyse_morph', models.TextField(null=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('lemma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lemme')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('difficulte', models.IntegerField(null=True)),
                ('age_recommande', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AddField(
            model_name='lemme',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.niveau'),
        ),
        migrations.AddField(
            model_name='lemme',
            name='synonymes',
            field=models.ManyToManyField(related_name='synonymes', to='core.lemme'),
        ),
        migrations.AddField(
            model_name='lemme',
            name='synonymes_valides',
            field=models.ManyToManyField(related_name='synonymes', to='core.lemme'),
        ),
        migrations.AddField(
            model_name='example',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lemme'),
        ),
        migrations.AddField(
            model_name='definition',
            name='lemme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lemme'),
        ),
        migrations.AddField(
            model_name='conjugaison',
            name='lemme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lemme'),
        ),
        migrations.AddIndex(
            model_name='lemme',
            index=models.Index(fields=['lemme'], name='core_lemme_lemme_602bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='lemme',
            index=models.Index(fields=['id'], name='core_lemme_id_a679d4_idx'),
        ),
    ]
